blank_issues_enabled: true
contact_links:
  - name: 💬 START HERE -- xCAD Discussions
    url: https://codeberg.org/xCAD/xCAD_discussions
    about: You are encouraged to discuss the problem you are seeing on the xCAD Discussions page before opening an issue here
